### ISSUE TITLE
Local Check Configurations - New.. button disappear

### ISSUE THREAD

**Issue by Dove21** [checkstyle/eclipse-cs#325] opened 2021-10-11 14:20 UTC
After the second time the Project Properties for Checkstyle are opened then "New.." button in "Local Check Configurations" disappear and instead there is "Set as Default" button (even when there is no configuration).

### To replicate:
1. Open Checkstyle Properties for project (Right click on project -> Properties -> Checkstyle)
2. Close the Properties window (Click Cancel)
3. Open Checkstyle Properties for project and check "Local Check Configurations" tab (Right click on project -> Properties -> Checkstyle -> "Local Check Configurations" tab)

See:
![obrazek](https://user-images.githubusercontent.com/2472208/136789995-a8edfb6b-ba9c-4b48-b91c-6257be1876f1.png)

### Configuration used:
Eclipse: 2021-09
Eclipse Checkstyle Plug-in: 8.44

**Comment by Bananeweizen** [comment] 2023-09-16 14:42
Duplicate of #430

**Closed by Bananeweizen** 2023-09-16 14:42 UTC
