### ISSUE TITLE
NoClassDefFoundError on generation of Eclipse formatter settings from checkstyle.xml

### ISSUE THREAD

**Issue by melloware** [checkstyle/eclipse-cs#107] opened 2018-10-22 13:03 UTC
Eclipse 2018-09 (4.9.0) Java EE Edition
CheckStyle 8.12 plugin

Trying to generate my Eclipse formatter settings from my checkstyle.xml is generating this error.

```
!ENTRY org.eclipse.core.jobs 4 2 2018-10-22 08:39:30.452
!MESSAGE An internal error occurred during: "transformCheckstyle".
!STACK 0
java.lang.NoClassDefFoundError: org/eclipse/jdt/internal/ui/preferences/PreferencesAccess
	at net.sf.eclipsecs.core.transformer.FormatterConfigWriter.writeCleanupSettings(FormatterConfigWriter.java:95)
	at net.sf.eclipsecs.core.transformer.FormatterConfigWriter.writeSettings(FormatterConfigWriter.java:89)
	at net.sf.eclipsecs.core.transformer.FormatterConfigWriter.<init>(FormatterConfigWriter.java:81)
	at net.sf.eclipsecs.core.transformer.CheckstyleTransformer.transformRules(CheckstyleTransformer.java:124)
	at net.sf.eclipsecs.core.jobs.TransformCheckstyleRulesJob.runInWorkspace(TransformCheckstyleRulesJob.java:117)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by romani** [comment] 2018-10-23 00:33
@melloware , please share your checkstyle.xml to let reproduce the issue.

**Comment by melloware** [comment] 2018-10-23 11:11
Sure @romani it is attached...


[checkstyle.zip](https://github.com/checkstyle/eclipse-cs/files/2505866/checkstyle.zip)

**Comment by Bananeweizen** [comment] 2018-10-30 19:59
@melloware Are you running on Java 9 or higher by any chance? The class in question is still part of JDT according to the JDT git repository. Therefore I suspect this might be a side effect of the module system and the changed class loading eventually.

**Comment by melloware** [comment] 2018-10-30 20:01
No I am still on 1.8.  I launch with 1.8.  See config below..

```
-vm
C:/Tools/jdk1.8.0_181/bin
-startup
plugins/org.eclipse.equinox.launcher_1.5.100.v20180827-1352.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.1.800.v20180827-1352
-product
org.eclipse.epp.package.jee.product
-showsplash
org.eclipse.epp.package.common
--launcher.defaultAction
openFile
--launcher.defaultAction
openFile
--launcher.appendVmargs
-vmargs
-Dosgi.requiredJavaVersion=1.8
-Dosgi.instance.area.default=@user.home/eclipse-workspace
-XX:+UseG1GC
-XX:+UseStringDeduplication
--add-modules=ALL-SYSTEM
-Dosgi.requiredJavaVersion=1.8
-Dosgi.dataAreaRequiresExplicitInit=true
-Xms2048m
-Xmx2048m
--add-modules=ALL-SYSTEM
```

**Comment by vorburger** [comment] 2018-10-31 08:52
@melloware theoretically, your `C:/Tools/jdk1.8.0_181/bin` directory name could be another version... :smile_cat: perhaps you could also double check and share the output of some of those properties shown in the Eclipse UI About, just to be extra sure.

**Comment by melloware** [comment] 2018-10-31 10:51
@vorburger I have verified I don't even have a JDK 9 installed and that 1.8_181 is the correct version and is JDK 8.  Below is my Elipse->About information.

[eclipse.txt](https://github.com/checkstyle/eclipse-cs/files/2533932/eclipse.txt)

**Comment by Bananeweizen** [comment] 2018-10-31 11:00
I can reproduce this by running CS from my Eclipse IDE (on Java 8). I still don't understand the issue, however. Have to debug during the classloading, maybe.

**Comment by vorburger** [comment] 2018-11-23 13:59
Just FYI I've also just hit this one (currently running under Java 9):

```
eclipse.buildId=4.9.0.I20180906-0745
java.version=9.0.4
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_IN
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.java.product

org.eclipse.core.jobs
Error
Fri Nov 23 14:54:43 CET 2018
An internal error occurred during: "transformCheckstyle".

java.lang.NoClassDefFoundError: org/eclipse/jdt/internal/ui/preferences/PreferencesAccess
	at net.sf.eclipsecs.core.transformer.FormatterConfigWriter.writeCleanupSettings(FormatterConfigWriter.java:95)
	at net.sf.eclipsecs.core.transformer.FormatterConfigWriter.writeSettings(FormatterConfigWriter.java:89)
	at net.sf.eclipsecs.core.transformer.FormatterConfigWriter.<init>(FormatterConfigWriter.java:81)
	at net.sf.eclipsecs.core.transformer.CheckstyleTransformer.transformRules(CheckstyleTransformer.java:124)
	at net.sf.eclipsecs.core.jobs.TransformCheckstyleRulesJob.runInWorkspace(TransformCheckstyleRulesJob.java:117)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jdt.internal.ui.preferences.PreferencesAccess cannot be found by net.sf.eclipsecs.core_8.12.0.201808161509
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:460)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:422)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:414)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:153)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 7 more
```

**Comment by albertadevor** [comment] 2019-01-04 05:39
Having this issue as well (same stack trace and all). I can only reproduce the bug on version 4.10 of Eclipse, though. At Eclipse version 4.6 the formatter-profile is correctly created. Thought I would share in case it's at all helpful for debugging!

```
eclipse.buildId=4.10.0.I20181206-0815
java.version=1.8.0_191

```

**Comment by dkoznodii** [comment] 2019-01-10 11:57
Same issue. Any updates?

**Comment by lkoe** [comment] 2019-03-23 17:03
`PreferencesAccess` is an internal eclipse API, thats not really supposed to be used by plugins.
I suppose due to changes in current eclipse versions this doesn't work anymore.

The formatter-profile generating functionality has gone unmaintained for several years now.
This leaves 2 options:

- remove this feature alltogether
- someone steps up to contribute a fix

Since its broken right now, I'll go for the first alternative for the next release (8.19).

**Comment by melloware** [comment] 2019-03-23 17:14
I understand but this is an incredibly useful feature for Eclipse users.   Without having to try and manually line up formatter settings with CheckStyle settings.

**Comment by romani** [comment] 2019-03-23 19:33
@melloware, please step in to fix a problem.

**Comment by andreasaba68** [comment] 2019-04-17 09:51
> 
> 
> Having this issue as well (same stack trace and all). I can only reproduce the bug on version 4.10 of Eclipse, though. At Eclipse version 4.6 the formatter-profile is correctly created. Thought I would share in case it's at all helpful for debugging!
> 
> ```
> eclipse.buildId=4.10.0.I20181206-0815
> java.version=1.8.0_191
> ```

Hi @albertadevor et all
first thanks to Alberta to indicate that the function works with eclipse 4.6
as a **workaround** I:
- downloaded and installed [eclipse 4.6](http://www.eclipse.org/downloads/packages/release/neon/3)
- imported a sample project
- configured checkstyle plugin with sun first and google checks second
- exported the settings
.. and I'm contributing them [here](http://www.eclipse.org/downloads/packages/release/neon/3) for those that are just using those "plain-vanilla" settings.
For custom settings I think everybody may follow a process similar to what I explained before.

Hopefully the team may find a contributor to actually fix the issue too.

Best regards

**Comment by oconnelc** [comment] 2019-10-14 17:26
Is there any update on this problem? I'm still seeing this with:
- Eclipse: Version: 2019-09 R (4.13.0)
- Eclipse Checkstyle Project: Eclipse Checkstyle 8.18.0.201903231603

Is there at least a workaround?

**Comment by andreasaba68** [comment] 2019-10-15 06:33
@oconnelc I don't know about a solution but I provided a workaround myself just above, you may avail of that.

**Comment by jmax01** [comment] 2020-04-08 13:42
Just a note the functionality appears to work on Photon/4.8.0.

> Having this issue as well (same stack trace and all). I can only reproduce the bug on version 4.10 of Eclipse, though. At Eclipse version 4.6 the formatter-profile is correctly created. Thought I would share in case it's at all helpful for debugging!
> 
> ```
> eclipse.buildId=4.10.0.I20181206-0815
> java.version=1.8.0_191
> ```

**Comment by melloware** [comment] 2020-04-08 13:44
@jmax01 So Eclipse has basically reinstated this prive method?

**Comment by romani** [comment] 2020-04-08 13:48
@melloware , please recheck that it works on your side on new Eclipse, and lets close issue if it become to work again.

**Comment by melloware** [comment] 2020-04-08 13:54
Sorry just realized Photon 4.8 is old the latest version is 4.12 the user is just stating it worked up until 4.8.

**Comment by janknobloch** [comment] 2020-04-14 09:35
error still exists in (and most likely will stay if the class is not coming back..):

eclipse.buildId=4.15.0.I20200305-0155
java.version=1.8.0_242

Best
Jan

**Comment by romani** [comment] 2020-04-17 14:32
@Calixte , if generation of file is completely broken, can we disable button for now?
 to not let user enjoy exception.

**Comment by karypid** [comment] 2020-05-16 23:36
Please have a look at my suggestion on how to address this. Instead of integrating with the profile store directly, it should be enough to write the dead-simple XML files into the project folder itself. Then users can import themselves.

**Comment by epsilon-everma** [comment] 2020-07-09 08:11
> @karypid thanks for your solution, does the trick for me.

Mine too, thanks @karypid

**Comment by romani** [comment] 2020-07-09 14:46
@karypid , please create PR lets discuss your solution.

**Comment by mhagnumdw** [comment] 2020-08-14 19:20
Is there any workaround?

**Comment by romani** [comment] 2020-08-20 05:57
We have PR for this problem - https://github.com/checkstyle/eclipse-cs/pull/228
It is not yet merged only because last step was not done.

@Calixte , are we you to merge this PR ?

**Comment by romani** [comment] 2020-09-01 16:15
Fix is merged

**Closed** 2020-09-01 16:15 UTC
