### ISSUE TITLE
NoClassDefFoundError from NewlineAtEndOfFileCheck

### ISSUE THREAD

**Issue by eric-milles** [checkstyle/eclipse-cs#4] opened 2018-01-05 21:40 UTC
Eclipse Checkstyle 8.5.1 threw this error when a file did not end with a newline.  Seems the Guava dependency may be out-of-date.

```
java.lang.Error: Error was thrown while processing xyz.groovy
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:302)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:216)
	at net.sf.eclipsecs.core.builder.Auditor.runAudit(Auditor.java:158)
	at net.sf.eclipsecs.core.builder.CheckstyleBuilder.handleBuildSelection(CheckstyleBuilder.java:306)
	at net.sf.eclipsecs.core.builder.CheckstyleBuilder.build(CheckstyleBuilder.java:172)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:142)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: java.lang.NoClassDefFoundError: com/google/common/collect/RegularImmutableBiMap
	at com.google.common.collect.ImmutableMap.of(ImmutableMap.java:124)
	at com.google.common.collect.ImmutableMap.copyOf(ImmutableMap.java:443)
	at com.google.common.collect.ImmutableMap.copyOf(ImmutableMap.java:422)
	at com.puppycrawl.tools.checkstyle.DefaultConfiguration.getMessages(DefaultConfiguration.java:147)
	at com.puppycrawl.tools.checkstyle.api.AbstractViolationReporter.getCustomMessages(AbstractViolationReporter.java:93)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.log(AbstractFileSetCheck.java:168)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.log(AbstractFileSetCheck.java:153)
	at com.puppycrawl.tools.checkstyle.checks.NewlineAtEndOfFileCheck.readAndCheckFile(NewlineAtEndOfFileCheck.java:119)
	at com.puppycrawl.tools.checkstyle.checks.NewlineAtEndOfFileCheck.processFiltered(NewlineAtEndOfFileCheck.java:82)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:83)
	at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:319)
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:289)
	... 16 more
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.RegularImmutableBiMap cannot be found by net.sf.eclipsecs.checkstyle_8.5.1.201712211522
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:484)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 28 more
```

**Comment by romani** [comment] 2018-01-05 22:12
It will be hard to help users if they do not share file and config to reproduce. Some cases could be simple but some hard to reproduce.

@lkoe , can you recommend smth on desirable format of issue report and what details are required to share by user ?

in eclipse-cs sources I do not see special guava version.

**Comment by eric-milles** [comment] 2018-01-05 22:22
This is the Guava bundle that Eclipse Oxygen 4.7.2 + Eclipse-Checkstyle 8.5.1 has: com.google.guava_21.0.0.v20170206-1425.jar

The manifest for the net.sf.eclipsecs.checkstyle bundle does not specify a version of the exported package com.google.common.collect.  Nor does it specify x-internal or anything else on that export.  I have [argued in the past that it is dangerous](https://sourceforge.net/p/eclipse-cs/feature-requests/164/) for Checkstyle to be exporting packages for 3rd party libraries without indicating their version or tagging them for use by only other Checkstyle bundles.

**Comment by romani** [comment] 2018-01-05 22:50
checkstyle 8.5 had guava `23.2-jre` https://github.com/checkstyle/checkstyle/blob/dbbd00f58fd36c7c23e24e6652076b735b8e7c0c/pom.xml#L274

**Comment by lkoe** [comment] 2018-01-06 10:52
eclipse-cs uses checkstyle-*-all.jar and therefor includes the guava version bundle within.
The bundle `net.sf.eclipsecs.checkstyle` exports certain guava packages (com.google.common.base/cache/collect/io) with the exported version set to eclipse-cs's version (`version="8.5.1"` in this case).
This is done to allow downstream extensions - for instance custom check implementations - the use of those guava packages, similar as they would be able to do within an ant/maven runtime.
At the same time the version set should prevent accidental import of the checkstyle's guave packages by other, unrelated plugins.

Now, bundle `net.sf.eclipsecs.core` uses `Require-Bundle: net.sf.eclipsecs.checkstyle;visibility:=reexport` thus should be able to see the exported guava packages, so all should be fine and dandy.

When testing my self I could not reproduce the issue.
Strange is also why it only happens for `NewlineAtEndOfFileCheck`, because the exception occurs on a pretty central spot within Checkstyle core and should be triggered by pretty much any module producing a message.

**Comment by lkoe** [comment] 2018-01-13 15:12
@eric-milles please retry with latest 8.7.0 release, although nothing of consequence has been changed specifically
I still can't reproduce this, maybe this is an interaction with another installed plugin?

**Comment by eric-milles** [comment] 2018-01-16 23:15
Sorry, I'm trying to recreate with eclipse-cs 8.5.1 before testing 8.7.0 and can't quite seem to find the right conditions as before.  I think it comes down to OSGi can decide on whatever bundle that exports a package to be used for a bundle that imports that package.  And we're left with non-deterministic (at least from my perspective) behavior to recreate.

If you set proper versions on all 3rd-party exported packages and you either use Import-Package with version constraints or switch to Require-Bundle, you should be a proper citizen of OSGi.  IMHO, proper versions means if you have Guava 23.2 then one of your package exports would be something like com.google.common.collect;version="23.2".  And you would recheck these versions as part of pulling in new checkstyle-all revisions.  Even your com.puppycrawl.* exports from the net.sf.eclipsecs.checkstyle bundle should be versioned.

**Comment by Bananeweizen** [comment] 2018-01-17 12:35
I tend to agree with @eric-milles here. In our company we create big RCP applications. And we meanwhile use mostly require-bundle and rather little package imports, although the pure OSGI theory says different. Also our experience is that there are often third parties like Apache Commons, Guava etc. where incompatible changes occur in more recent versions, and without any changes in your own code, the resolved bundle versions change due to _outside_ bundles having other requirements than before. E.g. your bundles crash just because of installing an otherwise completely unrelated bundle. We now prefer the P2 update manager telling us that our bundle mix cannot be installed or upgraded, since then we actually see the problems more early.

**Comment by lkoe** [comment] 2018-01-30 13:40
@Bananeweizen any suggestions to what would need to be changed, effectively? 

eclipse-cs internally only uses `import-package` directives for Eclipse platform dependencies.
For importing Checkstyle classes and it's transitive dependencies (e.g. guava), `require-bundle` is used.
I don't quite see how other guava versions would be used.

**Comment by Bananeweizen** [comment] 2024-04-04 12:40
Closing, as this is surely not happening with the current version anymore. Also there is ongoing work to remove the Guava dependency completely from the plugin.

**Closed** 2024-04-04 12:41 UTC
Labels: bug
