### ISSUE TITLE
Properties for Checkstyle Problem doesn't show the Correct Group

### ISSUE THREAD

**Issue by rnveach** [checkstyle/eclipse-cs#476] opened 2023-02-06 06:09 UTC
Identified when working on https://github.com/checkstyle/eclipse-cs/issues/451 ,

I added `ImportControl` to the project and new violations show up. When I go to the properties dialog for the new Checkstyle Problem, I am told "Group" is "Other" for the check.

![image](https://user-images.githubusercontent.com/5427943/216895864-762bb8e7-4ad4-4d57-a71d-d97b4860927a.png)

However, Eclipse-CS' own configuration panel says it should be under "Imports". The only thing under "Other" is "Checker" and "TreeWalker".

![image](https://user-images.githubusercontent.com/5427943/216895966-be30dc3e-0b10-45d9-8630-dd0d1b6549e5.png)

I expected that we show the same group name on the properties dialog as our configuration dialog.

**Comment by rnveach** [comment] 2023-02-06 06:53
https://github.com/checkstyle/eclipse-cs/blob/dd602eb158f940803f702bb6c19d9d5ed206b9a1/net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/builder/Auditor.java#L317-L323

I find it interesting we look for the metadata and if it doesn't exist, we create fake metadata and put it under "Other". It seems odd we create a fake metadata and don't even pass it to `MarkerPropertyPage` to display on the dialog. It could just save a simple look up, and even still we should be able to operate without everything being faked into the metadata.

I haven't debugged to confirm, but it does look like this is the issue. `getSourceName` is most likely the FQCN and metadata is looking based on the simple check name (IE: `com.puppycrawl.tools.checkstyle.checks.imports.ImportControlCheck` versus `ImportControl`).

**Comment by Bananeweizen** [comment] 2023-02-06 14:33
> I haven't debugged to confirm, but it does look like this area is the issue. `getSourceName` is most likely the FQCN and metadata is looking based on the simple check name (IE: `com.puppycrawl.tools.checkstyle.checks.imports.ImportControlCheck` versus `ImportControl`).

That sounds very similar to what I experienced here: https://github.com/checkstyle/eclipse-cs/issues/397#issuecomment-1313985343, when I wrote that the metadata somehow changed over the runtime of the application.

**Comment by Bananeweizen** [comment] 2024-03-30 20:18
duplicate of #397

**Closed by Bananeweizen** 2024-03-30 20:18 UTC
Labels: approved
