### ISSUE TITLE
Checkstyle not working since new update (8.26, updated yesterday)

### ISSUE THREAD

**Issue by tslinardo** [checkstyle/eclipse-cs#190] opened 2019-11-16 00:04 UTC
Not getting any automatic warnings and getting the following error and stack trace when I try to check code with Checkstyle:
```
com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module 
TreeWalker - TreeWalker is not allowed as a parent of LineLength Please review
 'Parent Module' section for this Check in web documentation if Check is standard.
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:472)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:198)
	at net.sf.eclipsecs.core.builder.CheckerFactory.createCheckerInternal(CheckerFactory.java:255)
	at net.sf.eclipsecs.core.builder.CheckerFactory.createChecker(CheckerFactory.java:127)
	at net.sf.eclipsecs.core.builder.Auditor.runAudit(Auditor.java:140)
	at net.sf.eclipsecs.core.builder.CheckstyleBuilder.handleBuildSelection(CheckstyleBuilder.java:307)
	at net.sf.eclipsecs.core.builder.CheckstyleBuilder.build(CheckstyleBuilder.java:173)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:833)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:220)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:316)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:319)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:371)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:392)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:154)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:244)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: TreeWalker
 is not allowed as a parent of LineLength Please review 'Parent Module' section 
for this Check in web documentation if Check is standard.
	at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:147)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:198)
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:467)
	... 18 more
```

**Comment by rnveach** [comment] 2019-11-16 00:20
Duplicate of https://github.com/checkstyle/checkstyle/issues/7258

**Comment by pmahony893** [comment] 2019-11-29 14:12
Looks like this was caused by https://github.com/checkstyle/checkstyle/issues/2116. 
It strikes me that this is going to affect a lot of people, but I'm not sure how that can be addressed from within the plugin.

A fix is to either manually edit the config file and move the `LineLength` element to be a direct descendent of `Checker`, or (using the GUI) to remove the check and re-add it.

[Ping to https://github.com/checkstyle/checkstyle/issues/7258 as well...]

**Comment by romani** [comment] 2019-11-29 21:32
@pmahony893 , your provided correct ways to fix the issue.
config have to be updated.

sorry that sometime we have to break compatibility, and it force users to do extra actions on their side.

**Closed by romani** 2019-11-29 21:32 UTC

**Comment by stevehall19** [comment] 2020-02-11 16:21
it's fun how this just seemingly breaks checkstyle in eclipse and the only info I can find on the issue is this closed issue.

**Comment by romani** [comment] 2020-02-11 16:30
Just update config as shown in referenced commits

**Comment by stevehall19** [comment] 2020-02-11 19:18
When I update the the config as show, it breaks the maven-plugin

**Comment by rnveach** [comment] 2020-02-11 22:14
maven-checkstyle-plugin and eclipse-cs have to be set to the same version of checkstyle.

**Comment by stevehall19** [comment] 2020-02-11 22:34
Yes, I see the issue. We are using version 3.0.0 of the maven plugin, which uses version 8.19 of checkstyle. I will need to install an older version of the plugin than what is on the Eclipse Marketplace for this to work, as I probably will not be able to easily get this changed in the maven build just to support eclipse.

**Comment by rnveach** [comment] 2020-02-12 00:11
You can override the version of checkstyle in the maven plugin to match eclipse-cs.
Example: https://github.com/checkstyle/checkstyle/blob/master/pom.xml#L606-L610

If you are using the latest checkstyle-cs, just make sure you are using the latest version of the plugin itself. The checkstyle dependency then should match the eclipse-cs dependency.

**Comment by stevehall19** [comment] 2020-02-12 00:39
Overriding the checkstyle version in version 3.0 of the maven plugin resulted in an the maven plugin throwing an error saying the checkstyle version was incompatible. I updated the the maven plugin to the latest 3.1 version, which still uses checkstyle 8.19 by default, so overrode it to use 8.29. At this point, when I ran the maven build, as expected, it gave me the "Treewalker is not.." error. I then first moved the LineLength Module so it was a child of the Checker module and then commented it out altogether. In both cases, the build threw a nullpointer. 

I can get the eclipse plugin working with a checkstyle.xml file updated to handle the breaking change in version 8.26 of checkstyle. It appears the issue is with the maven plugin. That being said, I am stuck with the maven plugin for the time being. Am I correct that I will need to build the older version of the plugin and a local eclipse update site?

**Comment by rnveach** [comment] 2020-02-12 01:02
> In both cases, the build threw a nullpointer.

Can you provide the stack trace? I am unaware of any NPE from a version mismatch issue like this main post showed. All exceptions should be related to location mismatch, checker versus treewalker, or property undefined.

> Am I correct that I will need to build the older version of the eclipse plugin and a local eclipse update site?

If you feel that is the only way to fix your issue, then yes. I am not sure what else could be the problem from what I am reading. As long as both plugins use the same version of checkstyle, there should be no issue. Both plugins just pass the config to checkstyle to parse.

**Comment by romani** [comment] 2020-02-12 03:03
That is good, as plugin is synced in releases from 8.19 with core library, so if you upgrade version in maven plugin, you can find matching eclipse plugin by version.

**Comment by lkoe** [comment] 2020-02-12 22:11
> Am I correct that I will need to build the older version of the eclipse plugin and a local eclipse update site?

Older update site versions are archived at bintray, you can install them by entering the appropriate version URL as new update site in Eclipse
https://dl.bintray.com/eclipse-cs/eclipse-cs/

e.g. https://dl.bintray.com/eclipse-cs/eclipse-cs/8.19.0/

Make sure you uninstall a new version beforehand or else eclipse might not let you install the older one.

**Comment by Gaugiun** [comment] 2021-03-18 16:28
Maybe your checkStyle version too high, and the xml config can't match the lastest version. I try to user 7.x version instead of 8.41 version，it works successfully.
