### ISSUE TITLE
question: Since when checkstyle checks ttf files?

### ISSUE THREAD

**Issue by basinilya** [checkstyle/eclipse-cs#254] opened 2020-08-26 08:16 UTC
I recently upgraded from Eclipse `20180405-1200` with Checkstyle Plug-in	`8.8.0.201802200627`
to Eclipse `20200615-1200` with Checkstyle Plug-in	`8.35.0.202008141925` and noticed that certain project full build now takes several minutes and the progress view shows "Checking" for some unrelevant java file. The `procmon` tool, however, shows that eclipse.exe keeps reading a `ttf` file in a source folder. If I forbid access to that file checkstyle fails with internal error at `at com.puppycrawl.tools.checkstyle` (see below).

This was never such an issue with the older software. I do have some suppression config, but it doesn't include ttf files. Should it? Why didn't it hang before?

**Upd** the following didn't help:

    <module name="SuppressionSingleFilter">
      <property name="files"
        value=".+\.(?:txt|xml|csv|sh|thrift|html|sql|eot|ttf|woff|css|png)$"/>
      <property name="checks" value=".*"/>
    </module>

Stacktrace when file access permission revoked:

    com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing C:\myproject\src\resources\fonts\KlokanTechNotoSans-Bold.ttf
    	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:311)
    	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:221)
    	at net.sf.eclipsecs.core.builder.Auditor.runAudit(Auditor.java:146)
    	at net.sf.eclipsecs.core.builder.CheckstyleBuilder.handleBuildSelection(CheckstyleBuilder.java:307)
    	at net.sf.eclipsecs.core.builder.CheckstyleBuilder.build(CheckstyleBuilder.java:173)
    	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:832)
    	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
    	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:220)
    	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263)
    	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:316)
    	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
    	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:319)
    	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:371)
    	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:392)
    	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:154)
    	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:244)
    	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
    Caused by: java.lang.IllegalStateException: Cannot read source file: C:\myproject\src\resources\fonts\KlokanTechNotoSans-Bold.ttf
    	at com.puppycrawl.tools.checkstyle.filters.SuppressWithPlainTextCommentFilter.getFileText(SuppressWithPlainTextCommentFilter.java:421)
    	at com.puppycrawl.tools.checkstyle.filters.SuppressWithPlainTextCommentFilter.accept(SuppressWithPlainTextCommentFilter.java:391)
    	at com.puppycrawl.tools.checkstyle.api.FilterSet.accept(FilterSet.java:73)
    	at com.puppycrawl.tools.checkstyle.Checker.fireErrors(Checker.java:406)
    	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:299)
    	... 16 more
    Caused by: java.nio.file.AccessDeniedException: C:\myproject\src\resources\fonts\KlokanTechNotoSans-Bold.ttf
    	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
    	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
    	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
    	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:230)
    	at java.nio.file.Files.newByteChannel(Files.java:361)
    	at java.nio.file.Files.newByteChannel(Files.java:407)
    	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
    	at java.nio.file.Files.newInputStream(Files.java:152)
    	at com.puppycrawl.tools.checkstyle.api.FileText.readFile(FileText.java:202)
    	at com.puppycrawl.tools.checkstyle.api.FileText.<init>(FileText.java:169)
    	at com.puppycrawl.tools.checkstyle.filters.SuppressWithPlainTextCommentFilter.getFileText(SuppressWithPlainTextCommentFilter.java:418)
    	... 20 more

**Comment by romani** [comment] 2020-08-26 11:13
please try to downgrade to 8.34

We leaked damaged default values setup for Checkstyle modules in 8.35, sorry about this.

**Comment by basinilya** [comment] 2020-08-26 12:30
@romani I've downgraded, but the problem remains. Here's my suppression config:

      <module name="SuppressWithPlainTextCommentFilter">
        <property name="offCommentFormat" value="CHECKSTYLE\.OFF\: ([\w\|]+)"/>
        <property name="onCommentFormat" value="CHECKSTYLE\.ON\: ([\w\|]+)"/>
        <property name="checkFormat" value="$1"/>
      </module>
      <module name="SuppressionFilter">
        <property name="file" value="${config_loc}/checkstyle_suppressions.xml"/>
      </module>
      
      <module name="SuppressionSingleFilter">
        <property name="files" value="^(?!.+[.](?:java|js)$)"/>
        <property name="checks" value=".*"/>
      </module>

Actually, I have two copies of this file, absolutely identical with the exception of profile name XML comment. And when I switch between profiles, the ttf file is either checked or skipped. Or I can open and save a profile using UI without making changes. This also affects the behavior. It looks like the order in which the suppress modules are processed is undefined. Perhaps because of SuppressWithPlainTextCommentFilter it tries to find comments in the ttf file, but in recent versions it's ridiculously slow.

**Comment by romani** [comment] 2020-08-31 02:19
@basinilya , please share whole config.
https://checkstyle.org/config.html#Checker
Do look at all files by default, you can exclude files by https://checkstyle.org/config_filefilters.html#BeforeExecutionExclusionFileFilter

https://checkstyle.org/config.html#TreeWalker Only java files.

**Comment by basinilya** [comment] 2020-09-01 18:36
> please share whole config.

attached: [eclipse-cs-254-bad.zip](https://github.com/checkstyle/eclipse-cs/files/5158181/eclipse-cs-254-bad.zip)

**Comment by romani** [comment] 2020-09-02 04:54
>attached

Please try to put file as plain text, to let me review and help you from phone. My Laptop time is very limited.

Looks like problem is not related to plugin. It will help a lot if you be able to reproduce issue without plugin, for example by https://checkstyle.org/cmdline.html

You did upgrade from 8.8, it 2 years old release, a lot has changed by this time, it is hard to recall when and what changed.

**Comment by basinilya** [comment] 2020-09-02 05:38
Here's the latest config
[checkstyle.xml.txt](https://github.com/checkstyle/eclipse-cs/files/5160293/checkstyle.xml.txt)

**Comment by romani** [comment] 2020-09-02 14:50
Please read migration notes https://github.com/checkstyle/checkstyle/issues/2116
You need to define fileExtensions property

**Comment by basinilya** [comment] 2020-09-03 07:56
Thank you. It's clear now

**Comment by rnveach** [comment] 2021-09-01 04:43
I am closing this as the original question seems answered. Don't let this stop the conversation from continuing if needs be.

> I still think it's wrong to re-read the file in the filters on each event even if it's a valid source file. How about we implement AuditListener.fileStarted in the filter, cache the parsed suppressions, and clear them on fileStarted?

I am not understanding this question to answer, but this sounds like a requested change in checkstyle and not eclipse-cs. I would create an issue in that repo if you wish for a change.

**Closed by rnveach** 2021-09-01 04:43 UTC
